config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "about", to: "site#index"
  get "contact", to: "messages#new", as: "new_message"
  post "contact", to: "messages#create", as: "create_message"
  resources :comments
  resources :articles
  root to: redirect('/articles')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :text, presence: true
  mount_uploader :image, ImageUploader
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :commenter, :body, presence: true
  belongs_to :article
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end
#class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
#  devise :database_authenticatable,
#         :recoverable, :rememberable, :validatable
#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.new(article: @article)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :text, :date, :image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenter, :body, :date, :article_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new message_params

    if @message.valid?
      MessageMailer.contact(@message).deliver_now
      redirect_to new_message_url, notice: "Message received, thanks!"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, :size => 100 %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, :cols => "100", :rows => "10" %>
  </div>

  <div class="field">
    <%= form.hidden_field :date, :value => DateTime.now.strftime("%a %d %b %Y, %H:%M%p") %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <button type="submit" class="btn btn-success btn-sm">Save article</button>
  <button type="button" class="btn btn-secondary btn-sm" onclick="window.history.back()">Go back</button>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>
<% if user_signed_in? %>
  <a class="btn btn-primary btn-sm" href="/articles/new">New article</a>
<% end %>
<% @articles.each do |article| %>
  <h3><%= link_to article.title, article %></h3>
  <datestyle><%= article.date.strftime("%a, %d %b %Y") %></datestyle>
  <p><div class="truncate lines-3"><%= simple_format(article.text) %></div></p>
  <div style="font-style: italic; font-weight: bold"><%= link_to 'Keep reading...', article %></div>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h3> <%= @article.title %> </h3>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_article_path(@article), :class => "btn btn-info btn-sm" %>
  <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" %>
  <%= link_to 'Back', articles_path, :class => "btn btn-secondary btn-sm" %>
<% end %>
<div style="font-style: italic; font-size: 10px"><%= @article.date.strftime("%a, %d %b %Y") %></div>
<%= image_tag(@article.image_url, :width => 600) if @article.image.present? %>
<p><%= simple_format(@article.text) %></p>

<h4>Comments</h4>
<% @article.comments.each do |comment| %>
  <div>
    <p><strong><%= comment.commenter %></strong>, <datestyle>on <%= comment.date.strftime("%a %d %b %Y, %H:%M%p") %></datestyle></p>
    <p><%= comment.body %></p>
    <% if user_signed_in? %>
      <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" %></p>
    <% end %>
  </div>
<% end %>

<div style="margin: auto"><%= render 'comments/form' %></div>

app/views/comments/_form.html.erb
<%= form_with(model: comment = @comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :commenter %>
    <%= form.text_field :commenter, :size => 50 %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, :cols => "60", :rows => "10" %>
  </div>

  <div class="field">
    <%= form.hidden_field :date, :value => DateTime.now.strftime("%a %d %b %Y, %H:%M%p") %>
  </div>

  <div class="field">
    <%= form.hidden_field :article_id %>
  </div>

  <button type="submit" class="btn btn-success btn-sm">Post comment</button>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenter</th>
      <th>Body</th>
      <th>Date</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><%= comment.date %></td>
        <td><%= comment.article_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Date:</strong>
  <%= @comment.date %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="bgimg">
    <div class="caption">
      <span class="border">MOUNTAIN AT MY GATES</span>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar-dark justify-content-between" style="background-color: #282E34;">
    <a class="navbar-brand" href="/">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="/articles">Articles<span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="/about">About</a>
        <a class="nav-item nav-link" href="/contact">Contact</a>
      </div>
    </div>
    <form class="form-inline">
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "btn btn-dark btn-sm" %>
      <% else %>
        <%= link_to "Log in", user_session_path, :method => :post, :class => "btn btn-dark btn-sm" %>
        <%= link_to "Sign up", new_user_registration_path, :method => :get, :class => "btn btn-light btn-sm" %>
      <% end %>
    </form>
  </nav>
  <br />
  <div style="background-color: white;">
    <div class="container">
      <div>
        <%= yield %>
      </div>
    </div>
  </div>
  <br />
  <div class="bgimg">
    <div class="caption">
      <span class="border">Goodbye, see ya again!</span>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
  <footer>
    Mariam V. Maldonado, 2019.
  </footer>
</html>

app/views/messages/new.html.erb
<h1>Contact</h1>
<p>Put your complaints here.</p>
<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <p>Name</p>
  <%= f.text_field :name, placeholder: "Your name", :size => 50 %>
  <p>E-mail</p>
  <%= f.email_field :email, placeholder: "Your e-mail", :size => 50 %>
  <p>Message</p>
  <%= f.text_area :body, placeholder: "Write your message here", :cols => "60", :rows => "10" %>
  <button type="submit" class="btn btn-success btn-sm">Send</button>
<% end %>

app/views/site/index.html.erb
<h1>About</h1>
<p>This is a site made for learning purposes. I did it about FOALS because I really like them.</p>
<p>The background image is <a href="https://www.flickr.com/photos/stevenfoxall/8601873630/in/album-72157633115133405/">a great picture</a> taken by <a href="https://www.flickr.com/photos/stevenfoxall/">a guy called Steven, from England,</a> and was published <a href="https://creativecommons.org/licenses/by-nc-nd/2.0/">under the Attribution-NonCommercial-NoDerivs 2.0 Generic (CC BY-NC-ND 2.0) license</a>. There are not commercial purposes on this site.</p>